services:
  app:
    build: .
    # 添加这个策略
    pull_policy: never
    image: aqua-chroma
    container_name: aqua-chroma-app
    restart: unless-stopped
    ports:
      - "8010:8000"
    volumes:
      - aqua-chroma-data:/app/data
    env_file:
      - .env

volumes:
  aqua-chroma-data: